// Generated by scripts/generate-content-index.mjs. Do not edit by hand.
import enDocument0 from "./../../content/locales/en/where-it-begins.json";
import ruDocument0 from "./../../content/locales/ru/where-it-begins.json";

export const generatedDocuments = {
  en: [enDocument0],
  uz: [],
  ru: [ruDocument0],
} as const;
