"use client";

import JSZip from "jszip";
import Link from "next/link";
import { Download, FileJson, Upload } from "lucide-react";
import { useState } from "react";
import { locales, Locale } from "@/lib/content";

const starter = { schemaVersion: 1, id: "new-research-note", slug: "new-research-note", title: "", description: "", status: "draft", createdAt: new Date().toISOString().slice(0, 10), updatedAt: new Date().toISOString().slice(0, 10), section: "field-notes", tags: [], content: [{ type: "paragraph", text: "" }], related: [], references: [], seo: { title: "", description: "" } };

export default function PrivateEditor() {
  const [locale, setLocale] = useState<Locale>("en");
  const [documentText, setDocumentText] = useState(JSON.stringify(starter, null, 2));
  const [message, setMessage] = useState("Browser export only: files are downloaded for Git review and commit.");
  const importFile = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); if (!parsed.id || !parsed.title) throw new Error("Required id or title is missing."); setDocumentText(JSON.stringify({ ...parsed, updatedAt: new Date().toISOString().slice(0, 10) }, null, 2)); setMessage(`Loaded ${file.name}. Validate, then export.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not parse this JSON file."); } }; reader.readAsText(file); };
  const exportFiles = async (zipMode: boolean) => { try { const parsed = JSON.parse(documentText); if (!parsed.id || !parsed.title || !parsed.slug) throw new Error("Title, id, and slug are required."); const path = `content/locales/${locale}/${parsed.slug}.json`; if (!zipMode) { const blob = new Blob([JSON.stringify(parsed, null, 2) + "\n"], { type: "application/json" }); download(blob, `${parsed.slug}.${locale}.json`); } else { const zip = new JSZip(); zip.file(path, JSON.stringify(parsed, null, 2) + "\n"); zip.file("README.txt", `Field / Notes ${locale.toUpperCase()} translation export. Review, then add to the repository.\n`); download(await zip.generateAsync({ type: "blob" }), `${parsed.slug}-${locale}-export.zip`); } setMessage(`Exported ${path}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Export validation failed."); } };
  return <main className="editor-shell"><header className="editor-topbar"><div><span className="wordmark">FIELD / NOTES<span>01</span></span><span className="editor-label">Private editor</span></div><Link className="text-link" href="/">Leave editor</Link></header><div className="editor-layout"><aside className="editor-sidebar"><p className="eyebrow">Workroom</p><h1>Export desk</h1><p>Author one translation at a time. Stable document and relationship IDs stay shared across languages.</p><label className="upload-button"><Upload size={16} /> Import JSON<input type="file" accept="application/json" onChange={importFile} /></label><div className="editor-note"><FileJson size={17} /><span>Translation path: <strong>content/locales/{locale}/</strong></span></div></aside><section className="editor-panel"><div className="panel-heading"><div><p className="eyebrow">Document translation</p><h2>Current draft</h2></div><span className="validation-message">{message}</span></div><div className="translation-toolbar"><label htmlFor="translation-locale">Editing language</label><select id="translation-locale" value={locale} onChange={(event) => setLocale(event.target.value as Locale)}>{locales.map((code) => <option value={code} key={code}>{code.toUpperCase()}</option>)}</select><span className="translation-status">{locale === "en" ? "Default language" : "Independent translation"}</span></div><textarea value={documentText} onChange={(event) => setDocumentText(event.target.value)} spellCheck={false} aria-label="Document JSON editor" /><div className="editor-actions"><button className="button button-secondary" onClick={() => exportFiles(false)}><Download size={16} /> Export JSON</button><button className="button button-primary" onClick={() => exportFiles(true)}><Download size={16} /> Finish & export ZIP</button></div></section></div></main>;
}

function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }
