import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Clock3, GitBranch } from "lucide-react";
import { notFound } from "next/navigation";
import { getDocument, getDocuments, getLocale, getUi, locales, readingTime, sectionLabel, Locale } from "@/lib/content";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";

export function generateStaticParams() { return locales.flatMap((locale) => getDocuments(locale).map((document) => ({ locale, slug: document.slug }))); }

export default async function ResearchPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale: rawLocale, slug } = await params;
  const locale = getLocale(rawLocale) as Locale;
  const ui = getUi(locale).ui;
  const document = getDocument(slug, locale);
  if (!document) notFound();
  const documents = getDocuments(locale);
  const headings = document.content.filter((block) => block.type === "heading");
  return <main className="site-shell document-shell"><header className="topbar"><Link className="wordmark" href={`/${locale}`}>FIELD / NOTES<span>01</span></Link><div className="document-tools"><LanguageSwitcher locale={locale} slug={document.slug} /><Link className="back-link" href={`/${locale}`}><ArrowLeft size={15} /> {ui.back}</Link><span className="doc-counter">{String(documents.findIndex((item) => item.id === document.id) + 1).padStart(2, "0")} / {String(documents.length).padStart(2, "0")}</span></div></header><div className="document-layout"><aside className="document-aside"><p className="eyebrow">{sectionLabel(document.section)}</p><nav className="toc" aria-label={ui.onPage}><span className="toc-title">{ui.onPage}</span>{headings.map((heading) => <a href={`#${heading.id}`} key={heading.id}>{heading.text}</a>)}</nav><div className="aside-bottom"><span>{ui.updated} {document.updatedAt}</span><span><GitBranch size={14} /> {document.related.length} {ui.connected}</span></div></aside><article className="research-document"><div className="document-kicker"><span>{ui.researchNote}</span><span className="status-dot" /> {document.status}</div><h1>{document.title}</h1><p className="document-lede">{document.description}</p><div className="document-meta-line"><span><Clock3 size={15} /> {readingTime(document)} {ui.minutes}</span><span>{document.publishedAt}</span><span>{ui.edited} {document.updatedAt}</span></div><div className="rich-content">{document.content.map((block, index) => { if (block.type === "heading") return <h2 id={block.id} key={index}>{block.text}</h2>; if (block.type === "callout") return <aside className={`callout ${block.tone}`} key={index}><strong>{block.title}</strong><p>{block.text}</p></aside>; if (block.type === "code") return <pre key={index}><code>{block.text}</code></pre>; return <p key={index}>{block.text}</p>; })}</div><section className="related-block"><p className="eyebrow">{ui.continue}</p><div className="related-grid">{document.related.map((id) => { const related = documents.find((item) => item.id === id) ?? getDocument(id, locale); return related ? <Link href={`/${locale}/research/${related.slug}`} key={id}><span>{sectionLabel(related.section)}</span><strong>{related.title}</strong><ArrowUpRight size={16} /></Link> : null; })}</div></section><section className="references"><p className="eyebrow">{ui.references}</p>{document.references.map((reference) => <a href={reference.url} target="_blank" rel="noreferrer" key={reference.title}><span>{reference.type}</span><strong>{reference.title}</strong><small>{reference.author}</small><ArrowUpRight size={15} /></a>)}</section></article></div></main>;
}
